### ISSUE TITLE
can't start a fresh app with scribd_fu 2.0

### ISSUE THREAD

**Issue by jerome** [mdarby/scribd_fu#1]
ipaper_access_key and ipaper_id columns must be created before setting scribd_fu with config.gem else relative error to missing columns are raised.

this is ok in development mode (first migrate, then edit environment.rb to add gem); it is however difficult to deploy it in production !

**Comment by jastix** [comment]
same issue for a 4 months now

**Comment by jerome** [comment]
The check_fields shouldn't be called at startup (check_environment) but before upload_to_scribd I guess...

**Comment by mdarby** [comment]
Don't remember the ticket from four months ago, but preliminary testing shows no issue... Will look into it tomorrow.

**Comment by mickey** [comment]
same issue here ...

**Comment by mdarby** [comment]
Nixed the checking of DB fields. Closed by 9d7bb4ce3c41cfc7f3a9897d3e58a91103253b5a

**Comment by mickey** [comment]
Thanks it's working now =)
