### ISSUE TITLE
Not rendering in Chrome/Windows

### ISSUE THREAD

**Issue by VikVenkat** [mdarby/scribd_fu#11]
Had to finagle the  source a bit to get Scribd_fu to work in Windows (I'll try to put this back up soon). 

Now am having an issue with rendering the file-view in Chrome. It works fine in internet explorer, so not sure what the issue is. 

I'm also a bit of a rails noob, and may be doing something silly.

**Comment by mdarby** [comment]
Hard to say without an example; I don't have a windows box available. Considering that this response is epically late, I'm going to hope you've solved this and close the issue.

**Comment by VikVenkat** [comment]
We did solve this, though I have forgotten the specifics of the solution.
(if anyone else has this problem, I'll point them at my repo)
