### ISSUE TITLE
Failed to convert error

### ISSUE THREAD

**Issue by scottmessinger** [mdarby/scribd_fu#2]
I'm using paperclip and after I attach the file and it seems to work. The console shows:

Processing AssetsController#create (for 127.0.0.1 at 2010-03-21 17:52:18) [POST]
  Parameters: {"commit"=>"Create Asset", "action"=>"create", "authenticity_token"=>"htg56mpBkJcMU1hqzS/L4Gm0pHzL0lM/L4+dYjblnMk=", "controller"=>"assets", "asset"=>{"assetable_type"=>"Resource", "assetable_id"=>"205", "asset"=>#File:/var/folders/Gp/Gp1sGZIQHCGtTTeb3AOUUE+++TI/-Tmp-/RackMultipart20100321-71799-1xyusyu-0}}
  User Load (0.5ms)   SELECT \* FROM "users" WHERE ("users"."id" = '9') LIMIT 1
  User Update (0.4ms)   UPDATE "users" SET "updated_at" = '2010-03-21 21:52:18', "last_request_at" = '2010-03-21 21:52:18' WHERE "id" = 9
  Asset Create (18.0ms)   INSERT INTO "assets" ("ipaper_access_key", "created_at", "asset_file_name", "updated_at", "asset_file_size", "ipaper_id", "assetable_type", "asset_content_type", "assetable_id", "description", "asset_updated_at") VALUES(NULL, '2010-03-21 21:52:18', '1_1_Receipt_Dec_2007.pdf', '2010-03-21 21:52:18', 17803, NULL, 'Resource', 'application/pdf', 205, NULL, '2010-03-21 21:52:18')
[paperclip] Saving attachments.
[paperclip] saving assets/44/original.pdf
  Asset Update (0.2ms)   UPDATE "assets" SET "updated_at" = '2010-03-21 21:52:21', "created_at" = '2010-03-21 21:52:18', "ipaper_id" = 28714976, "asset_file_size" = 17803, "asset_updated_at" = '2010-03-21 21:52:18', "assetable_id" = 205, "asset_file_name" = '1_1_Receipt_Dec_2007.pdf', "ipaper_access_key" = 'MY KEY', "asset_content_type" = 'application/pdf', "assetable_type" = 'Resource' WHERE "id" = 44
[paperclip] Saving attachments.
Rendering assets/create
Rendered units/edit/_asset (1.0ms)
Completed in 2315ms (View: 3, DB: 0) | 200 OK [http://localhost/assets]

However, when I display the ipaper, I get an error that says "failed to convert."

When I go into the console, I get this:

> > Asset.find(44).conversion_successful?
> > => nil
> > 
> > Asset.find(44).scribdable?
> > => false
> > 
> > Asset.find(44).upload_to_scribd
> > => nil

Why is this?

**Comment by scottmessinger** [comment]
I figured it out--I was trying to upload a *.png file which Scribd doesn't create previews for.

**Comment by mdarby** [comment]
Sorry, I totally missed the notification of this issue. Glad to hear you figured it out.
