### ISSUE TITLE
rails 3 deprecation warnings

### ISSUE THREAD

**Issue by shwoodard** [mdarby/scribd_fu#3]
a rails3 branch would be nice ;)

**Comment by mdarby** [comment]
What warnings are you getting? I'm not on Rails 3 yet..

**Comment by shwoodard** [comment]
DEPRECATION WARNING: RAILS_ROOT is deprecated! Use Rails.root instead. (called from /Users/sam/.rvm/gems/ree-1.8.7-2010.01/bundler/gems/scribd_fu-9bad1b23bfc6782a792c0cad1108c407a24c10c1-master/lib/scribd_fu.rb:3)

**Comment by mdarby** [comment]
Rails3 ready.
