### ISSUE TITLE
Document Not Uploading to Scribd on Update

### ISSUE THREAD

**Issue by jaredbrown** [mdarby/scribd_fu#4]
In the update action of my resumes controller I am doing the following:

@resume.update_attributes(params[:resume])

It's my understanding that this should trigger the after_save observer in scribd_fu.  Though while paperclip acts accordingly (deletes existing document, uploads new document) scribd_fu is not acting appropriately.  The document is not uploaded to scribd_fu.

My first question is: Why is after_save not being called?

Second question: Can support be added to delete the existing converted scribd file and upload the new document when the file_path parameter is not nil?

**Comment by mdarby** [comment]
`after_save` is being called, but it dies silently as `@object.ipaper_id` is already present (the document was already successfully uploaded to Scribd).

Support can be added for this behavior, I accept patches! :)

**Comment by perchard** [comment]
It would probably be a better idea to update the existing document with a new version than delete the existing document and uploading a new one.
