### ISSUE TITLE
Rails 3.0.3: scribd_fu.yml not found

### ISSUE THREAD

**Issue by seizmo** [mdarby/scribd_fu#7]
Using Rails 3.0.3, the file scribd_fu.yml is not found in config. It seems that neither ::Rails.root.to_s nor RAILS_ROOT seem to contain anything. ConfigPath is therefore set to "/config/scribd_fu.yml". 

If I just set ConfigPath to "config/scribd_fu.yml", the plugin works without problems.

**Comment by jerome** [comment]
+1

**Comment by perchard** [comment]
I am also experiencing this issue.

**Comment by victorlhlam** [comment]
the gem config file is still using RAILS_ROOT, which is deprecated with Rails3. the current version 2.0.9 is not really updated. mickey updated the code. would Matt help us to update the gemcutter? Thanks :)

**Comment by mdarby** [comment]
Wow, I'm very sorry I missed all these issues. For some reason Github's notification have not been working for me for (obviously) quite some time...

**Comment by mdarby** [comment]
I'm assuming this was fixed in another merge -- I've been out of the loop and need to reinvestigate
